require("aimi.plugins-setup") -- should at the top
require("aimi.core.options")
require("aimi.core.keymaps")
require("aimi.core.colorscheme")
require("aimi.plugins.nvim-cmp")
require("aimi.plugins.lualine")
require("aimi.plugins.comment")
require("aimi.plugins.nvim-tree")
require("aimi.plugins.treesitter")
require("aimi.plugins.autopairs")
require("aimi.plugins.gitsigns")
require("aimi.plugins.illuminate")
require("aimi.plugins.impatient")
require("aimi.plugins.lsp")
